### ISSUE TITLE
VUE 2 forms not displaying in Production mode

### ISSUE THREAD

**Issue by davidpede** [eclipsesource/jsonforms#1837]
### Describe the bug

I'm fairly new to VUE and am trying to use Jsonforms VUE 2 in a component. It's working great in development mode but when building in webpack using production mode the form is replaced in the page by a comment like this:

`<!--function(t,n,r,i){return zt(e,t,n,r,i,!0)}-->`

My webpack config:
```
const { VueLoaderPlugin } = require('vue-loader');
const webpack = require('webpack');

module.exports = [
    {
        mode: 'production',
        entry: './_build/assets/vue/vue.cmp.js',
        output: {
            path: '/foo/bar/',
            filename: 'vue.cmp.min.js'
        },
        resolve: {
            fallback: {
                "http": false,
                "https": false,
                "url": false,
                "path": false,
                "querystring": false
            }
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    loader: 'babel-loader',
                    exclude: /node_modules/,
                    options: {
                        presets: ['@babel/preset-env']
                    }
                },{
                    test: /.vue$/,
                    loader: 'vue-loader'
                },{
                    test: /\.(scss|sass)$/,
                    use: [
                        'style-loader',
                        'css-loader',
                        'sass-loader',
                    ],
                },{
                    test: /\.css$/,
                    use: [
                        'vue-style-loader',
                        'css-loader'
                    ]
                }
            ]
        },
        plugins: [
            new VueLoaderPlugin(),
            new webpack.ProvidePlugin({
                process: 'process/browser',
            })
        ]
    }
];
```

My component:
```
<template>
    <div class="row no-gutters">
        <div class="col-12 rounded">
            <v-card>
                <v-toolbar flat class="rounded">
                    <v-toolbar-title><h4 class="mb-0">Editing {{ panel.title }}</h4></v-toolbar-title>
                    <v-spacer></v-spacer>
                    <v-btn
                        color="primary"
                        large
                        class="mr-4 text-white"
                    >
                        Save
                    </v-btn>
                    <v-btn
                        large
                    >
                        Back
                    </v-btn>
                </v-toolbar>
                <v-card-text
                    class="p-0"
                >
                    <v-container>
                        <v-row class="p-2">
                            <v-col cols="12">
                                <json-forms
                                    :data="data"
                                    :schema="schema"
                                    :uischema="uischema"
                                    :renderers="renderers"
                                    @change="onFormChange"
                                />
                            </v-col>
                            <v-col cols="12">
                                <vue-json-editor
                                    v-model="schema"
                                    :show-btns="true"
                                    :expandedOnStart="true">
                                </vue-json-editor>
                            </v-col>
                        </v-row>
                    </v-container>
                </v-card-text>
            </v-card>
        </div>
    </div>
</template>

<script>

import axios from "axios";
import { JsonForms } from '@jsonforms/vue2';
import { vanillaRenderers } from '@jsonforms/vue2-vanilla'
import vueJsonEditor from 'vue-json-editor';

export default {
    props:  ['config','panel'],
    components: {
        JsonForms,
        vueJsonEditor
    },
    data: () => ({
        renderers: Object.freeze(vanillaRenderers),
        data: {},
        schema: {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 3,
                    "description": "Please enter your name",
                    "i18n": "name"
                },
                "vegetarian": {
                    "type": "boolean",
                    "i18n": "vegetarian"
                },
                "birthDate": {
                    "type": "string",
                    "format": "date",
                    "i18n": "birth"
                },
                "nationality": {
                    "type": "string",
                    "enum": [
                        "DE",
                        "IT",
                        "JP",
                        "US",
                        "RU",
                        "Other"
                    ],
                    "i18n": "nationality"
                },
                "personalData": {
                    "type": "object",
                    "properties": {
                        "age": {
                            "type": "integer",
                            "description": "Please enter your age.",
                            "i18n": "personal-data.age"
                        },
                        "height": {
                            "type": "number",
                            "i18n": "height"
                        },
                        "drivingSkill": {
                            "type": "number",
                            "maximum": 10,
                            "minimum": 1,
                            "default": 7,
                            "i18n": "personal-data.driving"
                        }
                    },
                    "required": [
                        "age",
                        "height"
                    ]
                },
                "occupation": {
                    "type": "string",
                    "i18n": "occupation"
                },
                "postalCode": {
                    "type": "string",
                    "maxLength": 5,
                    "i18n": "postal-code"
                }
            },
            "required": [
                "occupation",
                "nationality"
            ]
        },
        uischema: {
            "type": "VerticalLayout",
            "elements": [
                {
                    "type": "HorizontalLayout",
                    "elements": [
                        {
                            "type": "Control",
                            "scope": "#/properties/name"
                        },
                        {
                            "type": "Control",
                            "scope": "#/properties/personalData/properties/age"
                        },
                        {
                            "type": "Control",
                            "scope": "#/properties/birthDate"
                        }
                    ]
                },
                {
                    "type": "Label",
                    "text": "Additional Information"
                },
                {
                    "type": "HorizontalLayout",
                    "elements": [
                        {
                            "type": "Control",
                            "scope": "#/properties/personalData/properties/height"
                        },
                        {
                            "type": "Control",
                            "scope": "#/properties/nationality"
                        },
                        {
                            "type": "Control",
                            "scope": "#/properties/occupation",
                            "options": {
                                "suggestion": [
                                    "Accountant",
                                    "Engineer",
                                    "Freelancer",
                                    "Journalism",
                                    "Physician",
                                    "Student",
                                    "Teacher",
                                    "Other"
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    }),
    mounted: function () {
        console.log(this);
        this.fetchItem();
    },
    methods: {
        onFormChange(event) {
            this.data = event.data;
        },
        fetchItem() {
            axios.get(this.config.apiUrl + 'sections/templates/' + this.config.params.id,
                {
                    params: this.axiosParams()
                })
                .then(response => {
                    this.section = response.data.data;
                })
                .catch(e => {
                    console.log({e}); //todo error handling
                })
        }
    }
}
</script>
```
There no errors shown when building and no errors in the console on page load.

Would really appreciate if anyone could advise what the issue might be with this.

### Expected behavior

Form should work as it does in development mode

### Steps to reproduce the issue

I run my webpack build with mode set to 'production'

### In which browser are you experiencing the issue?

Google Chrome 96.0.4664.45

### Framework

Vue 2

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi @davidpede, thanks for the report. Which version of `@jsonforms/vue2` and `@jsonforms/vue2-vanilla` are you using? Can you also post the versions of all your Vue packages from the `package-lock.json` or `yarn.lock`, especially from the composition API? We use `1.0.0-rc.3`, can you try pinning the composition API to the same version?

**Comment by davidpede** [comment]
Just to add to this I'm having the exact same issue using the `@jsonforms/vue2-vuetify` renderer as well

**Comment by sdirix** [comment]
Hi @davidpede, we reworked our build and now publish commonjs and ESM modules (see #1722).

Can you try with the beta releases, i.e. `3.0.0-beta.0`? I can no longer reproduce the issue with the JSON Forms Vue seed when updating to the beta release.

Note that we also updated to the latest versions of Vue2 and the `@vue/composition-api`, so you might need to update them too.

**Comment by davidpede** [comment]
@sdirix Many thanks for this, I've updated packages to latest versions and the issue is resolved

**Comment by nilsdjupvik** [comment]
I had the same issue with Vue 3 using Vite & rollup. I found that my own custom renderers were not working. The solution was to include the **rollup-plugin-cleanup** (like the vanilla renderer build does). That fixed the issue for me :) As I've spent many hours on this issue I wanted to let you all know :)

**Comment by bishopandco** [comment]
@nilsdjupvik can you explain further? I am using vue 3 + vite and I've installed the rollup-plugin-cleanup but still not seeing jsonforms w/ custom renderers.
